### ISSUE TITLE
Missing text in Top 5 Terms list

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#171]
The Top 5 term list is not consistent in showing Top filter terms. Only terms 2 - 5 have text. Term 1 is missing the term name.

See: https://files.slack.com/files-tmb/T02L6HQ0H-F7SPR2W04-efcc5c8db1/image_480.png

**Comment by c-w** [comment]
This is likely a side-effect of how we're storing the data. Basically if an event has N keywords, we'll store all combinations of those keywords in the database. In order to represent single-keywords, we'll use a placeholder empty string in the remaining two slots.

Concrete example:
- Assume we matched the keywords "foo", "bar", and "baz".
- We store all 1-combinations: ("foo", "", ""), ("bar", "", ""), ("baz", "", "")
- We store all 2-combinations: ("foo", "bar", ""), ("foo", "baz", ""), ("bar", "baz", "")
- We store all 3-combinations: ("foo", "bar", "baz")

As you can see, the empty string will always be the most common term in this schema. As such, we should just filter out the empty string in the top-terms list.

**Comment by c-w** [comment]
Removed the empty entries to fix this confusion:

![image](https://user-images.githubusercontent.com/1086421/34488008-bb8163be-efa4-11e7-9cbb-d9c13dca1008.png)
