### ISSUE TITLE
VM SKU filter in ARM template is not consistent with nodeSelector in helm chart

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#172]
ARM template allows all SKUs with local SSD, i.e. the full range of DS, L, GS, etc. VM sizes. CassaHelm chart only deploys Cassandra on a single VM SKU (L4s), see https://github.com/erikschlegel/charts/blob/spark-localssd/incubator/cassandra/templates/statefulset.yaml#L30 and https://github.com/erikschlegel/charts/blob/spark-localssd/incubator/cassandra/values.yaml#L10.

In clusters with VM size any other than L4S, the Azure deployment will finish successfully, i.e. the user thinks everthing is up and running, but fortis is not deployed because kubernetes is waiting with the Cassandra install until L4s nodes join the cluster.

Possible remedies:
* remove the nodeSelector for Cassandra from the helm chart
* restrict ARM template to L4S deployment only

Also, consider a Custom Script Extension as part of the template that will only finish successfully when fortis is up and running to avoid customer confusion when deployment reports success, but the deployment is up and running.

**Comment by c-w** [comment]
I believe that this should have been fixed since https://github.com/CatalystCode/project-fortis-pipeline/pull/225 where we made a change to pass the VM SKU to the Cassandra Helm chart.

For verification, I've successfully deployed the pipeline with DS4 VMs.

Totally agree with your need for a health-check script to verify that the interfaces and services came up correctly before saying that the deploy was successful. I've created a new issue for this: https://github.com/CatalystCode/project-fortis-pipeline/issues/236

@xtophs: Is there anything else we need to do before considering this here issue fixed?

**Comment by c-w** [comment]
Marking as critical since this blocks deployments.

**Comment by c-w** [comment]
Marking as resolved since I managed to deploy this on a non-L4 VM after the previously mentioned fixes to how the Helm chart is being called.

![image](https://user-images.githubusercontent.com/1086421/33573709-a35200fc-d904-11e7-8156-f5e05ae4014c.png)

![image](https://user-images.githubusercontent.com/1086421/33573743-bd235508-d904-11e7-9838-3063a4f0c7ba.png)
