### ISSUE TITLE
No easy way to clone a site. 

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#178]
There does not seem to be an easy way to retrieve config settings for a deployed fortis site.

Would be greatly helpful to retrieve site settings and deploy another site with the same settings as a starting point for a new site.

Example: UNDP may want to deploy sites with the same event stream configurations for different geographies. It appears that today every site needs to be set up from scratch or it requires data export / import from the underlying database, which an casual user can probably not perform.

**Comment by c-w** [comment]
Implementing this may have unexpected consequences since it'll require sharing the stream secrets between accounts. For secrets with rate-limits (e.g. Twitter), this may lead to unexpected side-effects like the usage of one site deteriorating the performance for another site.

From a technical point of view, we'd have to do the following to implement this feature:
1) Add a button in the admin interface to export the site.
2) Add a GraphQL endpoint that issues a [COPY request](https://www.datastax.com/dev/blog/simple-data-importing-and-exporting-with-cassandra) to Cassandra. As the rows come back, compress them and stream them to blob storage. When the process is done, notify the user and provide them the link to the blob.
3) Add a button in the admin interface to import a site from a given blob URL.
4) Add a GraphQL endpoint that takes the blob URL and issues a COPY request to populate the database from the file provided at the blob URL.

I'd estimate this at about 1 developer week of effort. @xtophs and @dmakogon Given the new information, is this still something you'd like to invest into?

**Comment by c-w** [comment]
Removing from Sprint 1 for now since it's not a super high priority item and we have more important tasks to focus on first.

**Comment by c-w** [comment]
As per #207, it would also be interesting to think about a way that configs can be shared in a sort of library. Not necessary for a V1 implementation though, but a future requirement to keep in mind when designing the export feature.

**Comment by c-w** [comment]
We should likely only export a subset of the tables (e.g. the tables storing events would be very large!) or provide the option to select the tables that should be exported.

**Comment by c-w** [comment]
The uploaded export files should be made available on a protected blob storage account and accessed via shared-access-signature URLs so that the database dumps aren't fully public. See the [CsvExporter](https://github.com/CatalystCode/project-fortis/blob/4c9c7664658f1c151944dd6132e8a8dec9f4b7cf/project-fortis-services/src/resolvers/shared.js#L210-L247) for reference which already implements this pattern. The time-to-live for the export URLs will have to be longer than the time-to-live for the CSV URLs though since we wouldn't expect someone to import a site within a few hours of exporting it. According to the [docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1) we can make shared-access-signature URLs for any time duration, so maybe we could make database export URLs valid for a month or so and alert the user of this expiry time in the UI.

**Comment by Smarker** [comment]
**Export site settings from Cassandra:**
* Why use a COPY request when you can add the csvExporter decorator to the sitesettings query endpoints? When exporting, couldn't you issue a query on a table to get all rows and save them as a csv in blob storage?

**Import site settings to Cassandra:**
* Only use `COPY FROM` to import datasets that have `< 2 million rows`. To import large datasets, use the `Cassandra bulk loader`. (May need to use this for events)

**Comment by c-w** [comment]
re: bulk loader: the use-case for cloning a site is mostly getting a base level of watchlist terms, site settings, etc. As such, we should never reach the 2 million row limit of the copy command since we wouldn't be touching the events table.

re: csvExporter: that's a great suggestion. Likely, an implementation will leverage the csvExporter. However, to import a site, we'll need to export multiple tables (e.g. sitesettings, watchlist and streams at a minimum) so we'll have to add something on top of the csvExporter, e.g. run the exporter multiple times and then package up the CSVs as a single archive which we can ingest via our seed data ingestion mechanism (see [Dockerfile](https://github.com/CatalystCode/project-fortis/blob/386afaa7c7647f0c66679c6d3f270cf2b77ed1bb/project-fortis-services/docker/Dockerfile#L42-L48) and [run-node.sh](https://github.com/CatalystCode/project-fortis/blob/386afaa7c7647f0c66679c6d3f270cf2b77ed1bb/project-fortis-services/docker/run-node.sh#L43-L52) in project-fortis-services).

**Comment by c-w** [comment]
Some more ideas on implementation:

- Have an endpoint that exports all the relevant tables to CSV and packages them up into a tar.gz file. See [seed-data.tar.gz](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/ops/storage-ddls/seed-data.tar.gz) as an example. The endpoint then uploads the archive to Azure blob storage and creates a shared-access-signature link for it using the [createFile](https://github.com/CatalystCode/project-fortis/blob/4c9c7664658f1c151944dd6132e8a8dec9f4b7cf/project-fortis-services/src/clients/storage/BlobStorageClient.js#L37-L65) helper.

- When deploying a new Fortis site, add an entry to the deployment UI that passes-through up the [FORTIS_SEED_DATA_URL](https://github.com/CatalystCode/project-fortis/blob/386afaa7c7647f0c66679c6d3f270cf2b77ed1bb/project-fortis-services/docker/Dockerfile#L42-L48) to the project-fortis-services being set up in Kubernetes (see [install-fortis-services.sh](https://github.com/CatalystCode/project-fortis/blob/386afaa7c7647f0c66679c6d3f270cf2b77ed1bb/project-fortis-pipeline/ops/install-fortis-services.sh#L50-L94)). When the instance starts, we'll populate the database with the exported data from the previously created endpoint.

This approach has the nice advantage that we'd leverage the same mechanism we use for local development setup in production for cloning sites which means less effort to implement this feature and removal of a "dev-only" code path.

**Comment by c-w** [comment]
Working on the import path for this since it'll also provide us an easy way to set up demo sites.

**Comment by c-w** [comment]
Verified import code-path to be working by setting up a site via deploy-to-azure that references the twitter seed data:

![image](https://user-images.githubusercontent.com/1086421/35447512-e3e70888-0285-11e8-906f-dc9859abbcf4.png)

**Comment by c-w** [comment]
Backend code for site export is now implemented:

![image](https://user-images.githubusercontent.com/1086421/35461798-52394270-02b7-11e8-8ffc-bb1e951511ec.png)

Sample exported site (rename to strip off the txt from the extension): [Fortis Dev.tar.gz.txt](https://github.com/CatalystCode/project-fortis-pipeline/files/1669256/Fortis.Dev.tar.gz.txt)

**Comment by c-w** [comment]
Potentially good icon for the site-export button in the frontend: https://www.materialui.co/icon/settings-backup-restore

**Comment by Smarker** [comment]
I like this [one](https://materialdesignicons.com/icon/export) as well for site export

**Comment by c-w** [comment]
That one is nice, unfortunately it's not part of our material-ui dependency so it'll be a bit more of a hassle to integrate.

```sh
$ find project-fortis-interfaces/node_modules/material-ui/svg-icons/ -name '*export*'
project-fortis-interfaces/node_modules/material-ui/svg-icons/communication/import-export.js
```

[import-export icon](https://www.materialui.co/icon/import-export)

**Comment by c-w** [comment]
What is left to do to complete this issue?

- [ ] Add a new graphql call to the exportSite endpoint. See [services/Admin/index.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/services/Admin/index.js#L6). The schema for the call that needs to be made can be found in [SettingsSchema.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-services/src/schemas/SettingsSchema.js#L5).
- [ ] Wire the call to the exportSite endpoint through into a new action in [actions/Admin/index.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/actions/Admin/index.js#L29).
- [ ] Add a new button into the admin UI, e.g. on the settings page next to the save button. See [AdminSettings.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/components/Admin/AdminSettings.js#L237-L239) for where to add the button. Ideally, the button will be in a new component to keep the existing component single-focused. The [backup-restore](https://www.materialui.co/icon/settings-backup-restore) icon would work well for the new button. It may be possible to re-use the [ShareButton.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/components/Insights/ShareButton.js) component entirely for this button (see last item in list for more information).
- [ ] When the new export-site button is clicked, trigger the new export-site action via `this.props.flux.actions.ADMIN` similar to what existing buttons are doing (e.g. [handleSaveSettings in AdminSettings.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/components/Admin/AdminSettings.js#L149)).
- [ ] When the response comes back, ensure that any errors get displayed to the user. See the [error handling](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/actions/Admin/index.js#L67) of the existing actions for reference.
- [ ] When the response comes back, ensure that the link to the exported site gets copied into the clipboard for the user and notify them of the success via a snackbar, showing them also the time at which the link will expire. You can use moment's [fromNow](https://momentjs.com/#relative-time) method to format the display of the expiry message nicely. See [ShareButton.js](https://github.com/CatalystCode/project-fortis/blob/08e8158b611f2f93ca2549ab258fd064442bdb3d/project-fortis-interfaces/src/components/Insights/ShareButton.js) for reference which implements both of these features already. The ShareButton is fairly general so it may be able to re-use it to implement this feature.

**Comment by c-w** [comment]
Re-assigning to myself since Rachel is out sick.

**Comment by c-w** [comment]
![image](https://user-images.githubusercontent.com/1086421/35815689-1d48b71e-0a67-11e8-92ac-a630217be6b2.png)
