### ISSUE TITLE
Can't reset map to configured geofence

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#187]
After zooming into the map, the only way to restore to the initial view is to refresh the page. Refreshing the page loses all other filter settings as well. 

Would be great to have a way to reset the map to the configured area.

**Comment by c-w** [comment]
This should be pretty easy to implement. We'll just need a button that sets the dataStore `bbox` to `targetBbox` in [DataStore.js](https://github.com/CatalystCode/project-fortis-interfaces/blob/5eea24b6de37d2b034ba87ec33db8b9e236bfa88/src/stores/DataStore.js#L42).

Looking at the code, we write to the `targetBbox` when the site comes up and then mutate `bbox` from there onwards to calculate what elements to show in the newsfeed and heatmap.

Estimate 1-2 developer days.

**Comment by c-w** [comment]
~~Some more details for how to tackle this:~~

1) ~~Add a button to the [dashboard component](https://github.com/CatalystCode/project-fortis-mono/blob/b8a84e0d3c470a10f911799be972aa27b9c1776b/project-fortis-interfaces/src/components/Insights/Dashboard.js). When the button is clicked, it should trigger a dashboard action in Flux via `this.props.flux.actions`.~~

2) ~~Add a new action to the [dashboard actions](https://github.com/CatalystCode/project-fortis-mono/blob/b8a84e0d3c470a10f911799be972aa27b9c1776b/project-fortis-interfaces/src/actions/Dashboard/index.js) that dispatches an event to reset the geo-fence.~~

3) ~~Wire-up the action in the [data-store](https://github.com/CatalystCode/project-fortis-mono/blob/b8a84e0d3c470a10f911799be972aa27b9c1776b/project-fortis-interfaces/src/stores/DataStore.js) to do the actual work of resetting the currently shown bounding box (`bbox`) to the initial value (`targetBbox`) and tell all components to update via `this.emit("change")`.~~

**Comment by c-w** [comment]
This could be a good upskilling task for @rachelnicole -- assignment pending being added to the CatalystCode org.

**Comment by c-w** [comment]
Down-grading to Low Priority since we now have deep linking (#173) which can be used to save/restore state. This would still be a great UX enhancement though, so definitely worth doing; just not a blocking issue anymore.

**Comment by c-w** [comment]
Note that we now have a nice [actions footer](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-interfaces/src/components/Insights/Dashboard.js#L219-L262) into which the button to trigger the geo-fence reset should be placed. Please take a look at existing action buttons like [HeatmapToggle](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-interfaces/src/components/Insights/HeatmapToggle.js#L7-L35) or [ShareButton](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-interfaces/src/components/Insights/ShareButton.js#L8-L46) for implementation of existing buttons which can be copied for this task. A nice icon for the new action button might be [material-ui/svg-icons/maps/map](https://www.materialui.co/icon/map).

Placing the new button into the scope of the dashboard also has the advantage of making implementation easier since we'll be able to re-use the [refreshDashboard](https://github.com/CatalystCode/project-fortis/blob/50553cc7eb1f09fe7ae303b73badfdbb34f8aab4/project-fortis-interfaces/src/components/Insights/Dashboard.js#L170-L173) function instead of having to implement a new action on the flux data-store.

As such, the implementation of this task now is as follows:

1) In the Dashboard component, create a new button in the action buttons toolbar as described above.
2) When the button is clicked, look up the original bounding box for the site (targetBbox must be somewhere in the Dashboard component's props... you can use the [react-devtools](https://github.com/facebook/react-devtools) to inspect the component and find the property).
3) Invoke refreshDashboard with all the same state as before except for replacing bbox with targetBbox.
4) This will cause the dashboard to update, keeping all filters the same except for resetting the bounding box to the original value configured for the site, discarding any potential movements that may have happened during the current user session.

**Comment by c-w** [comment]
In https://github.com/CatalystCode/project-fortis/pull/7, @rachelnicole mentioned:

> However, I noticed that while the states are correctly getting updated when the map reset button is clicked, the call to refreshDashboard isn't actually re-positioning the map.

The map in the Heatmap.js component displays the map area indicated by the bounds variable in its state ([code](https://github.com/CatalystCode/project-fortis/blob/cc7561c0fad1bcd6bc64a3a8df8964ed48c72c3e/project-fortis-interfaces/src/components/Insights/Maps/HeatMap.js#L125)). This variable is correctly initialized from the props when the component is created ([code](https://github.com/CatalystCode/project-fortis/blob/cc7561c0fad1bcd6bc64a3a8df8964ed48c72c3e/project-fortis-interfaces/src/components/Insights/Maps/HeatMap.js#L16)). When the component updates due to a props change in its parent e.g. because the bbox in the DataStore changed, the Heatmap calls through to moveMapToNewLocation ([code](https://github.com/CatalystCode/project-fortis/blob/cc7561c0fad1bcd6bc64a3a8df8964ed48c72c3e/project-fortis-interfaces/src/components/Insights/Maps/HeatMap.js#L80)). However, that method does not seem to care about the bbox in the props and instead will only move the map if the placeid in the props was changed ([code](https://github.com/CatalystCode/project-fortis/blob/cc7561c0fad1bcd6bc64a3a8df8964ed48c72c3e/project-fortis-interfaces/src/components/Insights/Maps/HeatMap.js#L84)).

So to start looking into a fix for the reported issue, I'd recommend to modify the moveMapToNewLocation method to also respect changes of bbox in the props. If that doesn't fix the issue, then look out for other discrepancies between the component's state and its props.

**Comment by rachelnicole** [comment]
@c-w that sounds like a great place to start, thank you
