### ISSUE TITLE
Opening Translated Feed Item does not show translated text

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#193]
Steps:

Translate a feed item with the Translate Button -> Item text is translated
Click on feed item to read the full text of the feed item -> text is displayed in original language

https://epicstuff.slack.com/files/U4VLP4QBS/F7U9CT6DD/image.png

**Comment by c-w** [comment]
This is because the pop-up re-fetches all the information to render the event in the pop-up. The fix for this is to pass the translated text as context to the pop-up so that it can be re-displayed.

Estimate 2-3 developer days to take care of all the intricacies of passing the state between the two components (e.g. ensure that the "translate" button is in the same state on both components).

**Comment by c-w** [comment]
We now have a translation button on the event details page (see https://github.com/CatalystCode/project-fortis-pipeline/issues/185) so resolving this since the user can now re-translate the event.

My original plan of passing the already translated content to the details pop-up won't work in practice because the text that was translated on the news feed is just a summary of the full article, so any translations of that text won't apply to the full text on the details page.
