### ISSUE TITLE
Feed Item text doesn't show keyword 

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#199]
Snippet doesn't select the paragraph with the matched keyword from a longer text. A side effect is that the user can not get a translated text showing the keyword in context at all because in order to see the paragraph with the keyword, the user has to expand to the item details, but the item details cannot be translated.

https://epicstuff.slack.com/files/U4VLP4QBS/F7TBRT89K/image.png

**Comment by c-w** [comment]
This is likely because the text contained matches for multiple keywords (e.g. FARC in the linked example) but the summarization logic only considers the first keyword and creates a snippet around that.

Here is the implementation of the text summary, based on Fortis-v1:

https://github.com/CatalystCode/project-fortis-spark/blob/bd2b124d908ed7ede819739b53efdada2b2cf43b/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/summary/KeywordSummarizer.scala#L21-L52

We'll need to update this to create a summary that contains snippets around all matched keywords, not just the first.

**Comment by c-w** [comment]
Suggested implementation to find a summary of length L
1) Find N, the number of keywords that are in the text
2) Divide the summary context length by N
3) Create a summary with the previously used algorithm for each keyword; each of these will be of length L/N
4) Join the summaries with the ellipsis character "…" to have an overall summary of length L

**Comment by c-w** [comment]
New summarization algorithm is implemented.
