### ISSUE TITLE
Improve post-deployment site configuration experience

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#207]
First run experience must be performable by a novice user without knowledge of low level packages like Cassandra.

Some ideas:
* Wizard driven config for sources
* Step-by-stp wizard for all required config steps (search terms, geo fence, sources)
* ~~import cloned config and customize from existing config~~ https://github.com/CatalystCode/project-fortis-pipeline/issues/178
* ~~Search based definition of geo fence, i.e. type location name and system will look up geo fence~~ https://github.com/CatalystCode/project-fortis/commit/cfe7afb4978e256baff0484fd1d0584a676b00e7
* ~~shared config library, i.e. new sites present a library of configs made available by other users~~ https://github.com/CatalystCode/project-fortis-pipeline/issues/178
* ~~curated configs made available from Microsoft or crowd sourcing~~ https://github.com/CatalystCode/project-fortis-pipeline/issues/178

**Comment by c-w** [comment]
Some comments on scope for this task:

We already have a nice UI for many settings and the geo-fence so we can solve any potential pain points with documentation here.

The main pain point for setting up a new Fortis site is configuring the streams that the site listens to, so this task should focus on that area first.

As for Christoph's other great suggestions, we can implement them later since they're more enhancements to the UX as opposed to blockers for setting up a new site.

**Comment by c-w** [comment]
Some comments on implementation of the improved streams editor:

The required or optional parameters for each stream type are documented in the project-fortis-spark repo. You can find them by looking at the usages of the connectorConfig object in the StreamFactorBase subclasses inside of the sources.streamfactories package. E.g.:

- [Bing: accessToken, searchInstanceId, keywords](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/BingPageStreamFactory.scala#L18-L20)

- [EventHub: namespace, name, policyName, policyKey, partitionCount, consumerGroup](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/EventHubStreamFactory.scala#L30-L41)

- [FacebookComment: appId, appSecret, accessToken](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/FacebookCommentsStreamFactory.scala#L19-L21)

- [FacebookPost: appId, appSecret, accessToken](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/FacebookPageStreamFactory.scala#L19-L21)

- [HTML: feedUrls, maxDepth, pollingPeriodInSeconds, cacheEditDistanceThreshold, userAgent](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/HTMLStreamFactory.scala#L17-L31)

- [InstagramLocation: authToken, latitude, longitude](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/InstagramLocationStreamFactory.scala#L17-L24)

- [InstagramTag: authToken, tag](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/InstagramTagStreamFactory.scala#L18-L20)

- [RSS: userAgent, connectTimeout, readTimeout, pollingPeriodInSeconds](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/RSSStreamFactory.scala#L19-L30)

- [Radio: radioUrl, audioType, locale, subscriptionKey, speechType, outputFormat](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/RadioStreamFactory.scala#L19-L24)

- [Reddit: applicationId, applicationSecret, keywords, subreddit, searchLimit, searchResultType](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/RedditStreamFactory.scala#L18-L22)

- [Twitter: consumerKey, consumerSecret, accessToken, accessTokenSecret, watchlistFilteringEnabled, userIds](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/TwitterStreamFactory.scala#L30-L149)

The MVP for this issue would be to make a UI where the Fortis site admin can set up and edit streams for their Fortis deployment via a nice UI that makes it easy to input all the parameters documented above for the stream.

We already have an API endpoint for modifying streams in project-fortis-services ([modifyStreams](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-services/src/resolvers/Settings/mutations.js#L239-L284)) and a UI on top of that endpoint in project-fortis-interfaces ([StreamEditor](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-interfaces/src/components/Admin/StreamEditor.js)).

The simplest implementation of this task would therefore be to add features to the [StreamEditor](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-interfaces/src/components/Admin/StreamEditor.js) to offer the user guidance on which parameters to input into this UI and do a little bit of validation to prevent obviously bad inputs from being persisted. Once this simple incremental step is done, we can circle back and check if we need to invest more time into improving the experience further.

The StreamEditor should also allow users to add new streams. This will require adding a new API endpoint project-fortis-services ([mutations.js](https://github.com/CatalystCode/project-fortis/blob/34fd118814bb8c3bc5381b5b45323a8884158927/project-fortis-services/src/resolvers/Settings/mutations.js#L348-L358)). No need to support deletion of streams for now since they can just be disabled as a work-around.

Rough tasks:

- [x] StreamEditor guides user on what types of streams can be added (see list above for valid options).
- [x] StreamEditor tells the users what params they need to add depending on the type of the stream.
- [x] StreamEditor verifies params for stream depending on the type of the stream.
- [x] StreamEditor enables user to add new streams.
- [ ] Update Admin docs with more detailed information on how to add streams and info on stream parameters

**Comment by c-w** [comment]
If you use `docker-compose up --build` with the current seed data, you'll have a great test-case for this issue. The seed site definition configures an RSS stream and a Twitter stream. The credentials for the latter are incorrect. Once this task is implemented, there should be a nice UI such that a non-technical user can edit those credentials and add new streams.

**Comment by Smarker** [comment]
**current status:**
* Have a create/edit stream inner component for each stream, which changes with dropdown selection

**next to do:**
* When user selects save after entering in values for a new stream, make sure the mutation is successful and that the new row appears in the list to the left
![image](https://user-images.githubusercontent.com/7232635/35462010-3e3478a2-02b8-11e8-9b2c-488eb61037f7.png)

**Comment by c-w** [comment]
This library from Mozilla looks like a decent one to auto-generate the forms to edit the parameters from a schema definition: https://mozilla-services.github.io/react-jsonschema-form/

**Comment by Smarker** [comment]
Stream Editor is ready, just waiting for final approval from @c-w as some more changes were made since the original review.

**Comment by c-w** [comment]
Hiding of stream access tokens from frontend is now implemented: https://github.com/CatalystCode/project-fortis/commit/9b8d009542cfea0160f29f8fdcf2a0330e59d8ce

**Comment by c-w** [comment]
Streams editor by @Smarker was merged in https://github.com/CatalystCode/project-fortis/pull/23 and is now being verified in production.

**Comment by c-w** [comment]
Going to resolve this given that the feature is implemented. If we find any problems with the workflow end-to-end, we'll open separate issues.
