### ISSUE TITLE
Suggestion: Color code Tags on item details

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#210]
Similar experience looking at pages in Google or Bing cache where tags found in the text are highlighted in different colors.
You could color each tag (and even each location) with a different color and then highlight matched accordingly in the text

![image](https://user-images.githubusercontent.com/8771377/32549224-a1501252-c456-11e7-8242-11f53fdbc5a1.png)

**Comment by c-w** [comment]
This may be non-trivial since the library we're using ([react-highlight-words](https://github.com/bvaughn/react-highlight-words)) doesn't have native support for multiple highlights.

I wonder if we can use the "highlightTag" argument to the Highlight component to implement the multi-color highlighting, e.g. to make a custom tag that can inspect its children for their text and modify the highlight color appropriately.

Relevant code: https://github.com/CatalystCode/project-fortis/blob/c8b3189e6b377e9b0973abea28cdb2d2860c99fe/project-fortis-interfaces/src/components/dialogs/EventDetails.js#L75-L79

**Comment by c-w** [comment]
I ended up re-implementing the highlighter component anyways (due to https://github.com/CatalystCode/project-fortis-pipeline/issues/186). With the new component, adding the custom colors per tag shouldn't be too hard.

Relevant code to modify: https://github.com/CatalystCode/project-fortis/blob/8dd37964f435cf706fa965a26c3ffec7e31127d7/project-fortis-interfaces/src/components/dialogs/Highlighter.js#L19-L28

**Comment by c-w** [comment]
Per place/tag highlight colors are now implemented:

![image](https://user-images.githubusercontent.com/1086421/34578535-5e899fea-f153-11e7-96dc-21a1a071b677.png)

**Comment by c-w** [comment]
Here's another screenshot that shows the effect nicely:

![image](https://user-images.githubusercontent.com/1086421/34578914-cc0d818e-f154-11e7-821d-9956fcd0c300.png)
