### ISSUE TITLE
Timeline pop up missing values

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#211]
Popup only displays one value, even though there are 10 lines in the graph.

Might be something specific to the chart widget, but it's confusing to the user.

![image](https://user-images.githubusercontent.com/8771377/32549296-e557a956-c456-11e7-8b15-34088deebf15.png)

**Comment by c-w** [comment]
I've only seen this happen in the case where there only is one data point for the selected index.

![image](https://user-images.githubusercontent.com/1086421/34530722-09df9006-f07e-11e7-9f13-a18d20af4894.png)

There is unfortunately no good way to customize the tooltip in recharts ([see docs](http://recharts.org/#/en-US/api/Tooltip)).

Closing this by design.
