### ISSUE TITLE
Site doesn't come up in IE

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#213]
Site sits there with loading message. No errors in F12

If IE is not supported, then we should display an "unsupported browser" page.

![image](https://user-images.githubusercontent.com/8771377/32549649-45ae9584-c458-11e7-9575-1ee269829ff2.png)

**Comment by c-w** [comment]
Looks like this is due to some JS we use which is not supported by IE, e.g.:

![image](https://user-images.githubusercontent.com/1086421/33626866-ce6290ac-d9c9-11e7-92eb-73d10af69747.png)

We can use a [browser detection plugin](https://www.npmjs.com/package/react-browser-detection) for React to not render for IE.

**Comment by c-w** [comment]
Given that the browser detection should be applied to all pages, we can implement it at the level of the [AppPage component](https://github.com/CatalystCode/project-fortis-mono/blob/b8a84e0d3c470a10f911799be972aa27b9c1776b/project-fortis-interfaces/src/routes/AppPage.js) which is our top-level component as shown in the [router configuration](https://github.com/CatalystCode/project-fortis-mono/blob/b8a84e0d3c470a10f911799be972aa27b9c1776b/project-fortis-interfaces/src/routes/routes.js#L10).

**Comment by c-w** [comment]
We should probably just support Chrome and Firefox since those are the browsers we used during development so we know that features should be working.

**Comment by c-w** [comment]
This should be a good upskilling task for @kwadwon -- assignment pending being added to the CatalystCode org.
