### ISSUE TITLE
Filters input fails intermittently

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#219]
* Pick a different filter in the filters input (rafaga, captura)
* either hit enter or tab out

Sometimes it works and sometimes it doesn't

**Comment by c-w** [comment]
This is now made consistent (at least on my test setup Win10+Chrome): disabled since [react-treebeard](https://github.com/alexcurtis/react-treebeard) does not seem to have first-class support for keyboard events.

Please re-open if you can still reproduce this with the latest master in [project-fortis](http://github.com/CatalystCode/project-fortis).
