### ISSUE TITLE
Improve usability of controls of time-series graph widget

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#221]
Time Window dropdown controls scope of the Timline chart, but they are in opposite corners of the page. 
Locating them closer together would make the relationship of the 2 widgets more intuitive / discoverable. 

Might even replace the "reset button" that doesn't seem to work.

**Comment by c-w** [comment]
Estimate 1-2 days for this.

**Comment by c-w** [comment]
The "reset button" is the one highlighted in blue in the screenshot below:

![image](https://user-images.githubusercontent.com/1086421/34499773-9b244e20-efd5-11e7-8d40-84c214fd8b58.png)

You may notice the little white slider under the time series graph (this was non obvious to me at first, should improve this). It's possible to zoom in on a particular time slice using that slider. The reset button restores the previous view, but for some reason does not update the rest of the dashboard (maybe because the user is expected to hit the "reload" button?). Similarly, the button highlighted in red in the screenshot above will take the current slider time selection and set the time range for the full dashboard to the custom time interval.

To make the UI clearer, I recommend the following actions:

1) Add hover text over the white slider explaining its functionality.
2) Disable the two control buttons unless the white slider has been used to avoid the confusing of user clicking the buttons and nothing happening.
3) Improve the labeling of the buttons to make functionality clearer.
4) Move time dropdown widget and timeline widget to same side of page.

**Comment by c-w** [comment]
Time dropdown is now closer to the graph widget:

![image](https://user-images.githubusercontent.com/1086421/34526742-681c9068-f071-11e7-8e62-5ea4fe661a8b.png)

**Comment by c-w** [comment]
Improved UI consistency by making the data source selector the same widget as the date selector:

![image](https://user-images.githubusercontent.com/1086421/34528016-812f18e2-f075-11e7-9927-1bb072aebbc4.png)

**Comment by c-w** [comment]
Added some labels to improve discoverability:

![image](https://user-images.githubusercontent.com/1086421/34528664-91916e90-f077-11e7-9f88-7d45b6f1181e.png)

**Comment by c-w** [comment]
All of these changes should have improved usability significantly, so resolving this issue. If you have other ideas for how to improve the usability further, please re-open -- I have limited UX experience so always happy to hear how to make UIs more usable.
