### ISSUE TITLE
Implement admin panel user management

### ISSUE THREAD

**Issue by c-w** [CatalystCode/fortisdeploy#249]
In https://github.com/CatalystCode/project-fortis-pipeline/issues/176 we implemented authentication and authorization via MSAL and it's now possible to specify users and admins for Fortis at site creation time.

We should have a tab in the admin panel to edit the users table.

Assigning to @Smarker since they authored the original admin panel tabs.

**Comment by Smarker** [comment]
Need to add documentation on the ability to specify users and admins at site creation/update screenshot of site creation.

**Questions:**
* Should an admin be allowed to create/delete users in the table or just edit?
* Should an admin only be allowed to elevate a user's role to admin? Or can an admin change the status of another admin to a user role?
* Should you be allowed to edit the user's identifier field?
* If you are admin of the site, can you change your role to user? If so, I assume that the admin tab should then be hidden and unable to be accessed by the current user.
* I think I should also add the option for a user's role to be changed through the cli, so that the cli captures all that you can do on the site. Would it be sufficient to have the user provide their identity and if the identity is admin, then they can alter roles?

**Comment by Smarker** [comment]
Todo:
- [x] Add a tab on the admin site which would display a table of users. The user identity field would contain free-form input boxes and the role would contain dropdowns.

| User Identity | Role   |
|---------------|--------|
|  smarker@microsoft.com       | admin |
|  cwolf@microsoft.com           | admin |
|  bob@gmail.com             | user    |

**Current Status:**
![image](https://user-images.githubusercontent.com/7232635/34897248-1e48c992-f7bb-11e7-9921-3e1948fd1f5e.png)

- [x] Allow an admin to **add** users or other admin to the table. 
- [x] Allow an admin to **remove** users or other admin on the table (excluding themselves)

- [x] If an admin adds an admin role for user X and forgets to add a user role for user X, a **snackbar** will appear alerting the admin that a user role(s) were created for any admin added that were missing corresponding user roles. (likewise for delete - if a user X is deleted then admin X will also be deleted, since you cannot be an admin without being a user)

- [x] Allow the admin to **edit** roles or identities of the users on the table. An admin can demote another admin. Only admins should have access to the API (using the `requiresRole` decorator in the GraphQL service)

- [x] Add app insights logging for whenever a user is edited, created, or deleted

- [ ] edit - or remove ability to edit after saving the row so the user must only add or remove

Test:
- [x] highlighting on edit of cell
- [x] filter, sort
- [x] create new users
- [x] delete (one, many, rows with empty values)
- [x] logging
- [x] when removing or adding users, buttons always return to original state
- [x] number of rows selected in grid makes sense before and after delete

**Comment by c-w** [comment]
> Should an admin be allowed to create/delete users in the table or just edit?

An admin can create, delete and edit rows in the users table.

> Can you edit the identifier?

Yes, an admin can edit the identifier as well as the role.

> If you are admin of the site, can you change your role to user? If so, I assume that the admin tab should then be hidden and unable to be accessed by the current user.

Please disallow users from changing their own roles to prevent silly mistakes and people locking themselves out of the system.

> I think I should also add the option for a user's role to be changed through the cli, so that the cli captures all that you can do on the site. Would it be sufficient to have the user provide their identity and if the identity is admin, then they can alter roles?

Which CLI? If you're wondering about the [scripts](https://github.com/CatalystCode/project-fortis/tree/15eb268bb0b48027ef9eb00ce9144986d466ec0d/project-fortis-services/src/scripts) directory, that only contains helpers used during deployment/setup. This is not intended to be a full API. The GraphQL definition is our API.

**Comment by Smarker** [comment]
Oh, ok I was referring to the scripts CLI.

**Comment by Smarker** [comment]
Do we also need a service bus message to be sent on create/edit/delete of a user?

**Comment by c-w** [comment]
No. ServiceBus controls project-fortis-spark. Authentication and authorization are handled entirely at the project-fortis-services level.

**Comment by Smarker** [comment]
Ok. And must the identity be an email or any string?

**Comment by c-w** [comment]
It should likely always be an email, but might as well keep it unrestricted at any string.

**Comment by c-w** [comment]
PR: https://github.com/CatalystCode/project-fortis/pull/3

**Comment by c-w** [comment]
Excellent, thanks @Smarker!
